### PR TITLE
setAmbientResolution()

### PR DESCRIPTION
**Pull request by mikeysklar**
Tested on MCP9600. Added setAmbientResolution() and included minimal example code. Runs well as expected with higher resolution Ambient readings.

Original example code unmodified also still runs correctly with lower resolution ambient readings.

Test with:
Arduino IDE 2.3.3 
Feather RP2040
MCP9600

This came out of a [forum request](https://forums.adafruit.com/viewtopic.php?t=214103) for controlling the resolution for the ambient temperature to match the resolution with  the thermocouple. I didn't think it would be a big deal, but it took me a day  to realize the datasheet had high / low resolution logic flipped. 

mcp9600-resolution

```
#include <Adafruit_MCP9600.h>

Adafruit_MCP9600 mcp;

// New variables for resolutions
Ambient_Resolution ambientRes = RES_ZERO_POINT_0625;
Thermocouple_Resolution thermocoupleRes = RES_14_BIT;

void setup() {
  Serial.begin(115200);
  while (!Serial) delay(10);

  if (!mcp.begin(0x67)) {
    Serial.println("Failed to find MCP9600 chip");
    while (1) { delay(10); }
  }

  // Set the resolutions
  mcp.setAmbientResolution(ambientRes);
  mcp.setThermocoupleResolution(thermocoupleRes);

  Serial.println("MCP9600 ready.");
}

void loop() {
  float ambientTemp = mcp.readAmbient();
  float thermocoupleTemp = mcp.readThermocouple();

  Serial.print("Ambient Temp: ");
  Serial.print(ambientTemp, 2);
  Serial.print(" C, Thermocouple Temp: ");
  Serial.print(thermocoupleTemp, 2);
  Serial.println(" C");

  delay(1000);
}
```

@ladyada

### CODE REVIEW

**Comment by mikeysklar** [comment]
@ladyada - The CircuitPython version did not need a setAmbientResolution() interface since the bits can easily be twiddled from user code. The original [forum issue](https://forums.adafruit.com/viewtopic.php?t=214103) was a request for setAmbientResolution() for Arduino library which I have added. @alian35 and I have both tested this and found it to be working as expected.

**Comment by ladyada** [comment]
yah wanna add it as a commented out (or not commented out) line in the exmaples so folks know its there?

**Comment by mikeysklar** [comment]
Good point. 

I added ambient resolution to the example sketch. Same format as the ADC settings.

Tested on Feather RP2040 with MCP9600.

I can order a MCP9601 to add equivalent there if you think that is a good idea.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
good idea to get the 9601 they are both annoyuing chips

**Comment by mikeysklar** [comment]
I ordered a 9601. I can update this PR or start a fresh one with the 9601 update.

**Pull request merged**
